version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    environment:
      - use_https=${USE_HTTPS:-false}
    depends_on:
      - api-gateway
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    external: true
