version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - microservices-network

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: api-gateway
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    networks:
      - microservices-network
    # For production readiness
    deploy:
      resources:
        limits:
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  microservices-network:
    driver: bridge

volumes:
  redis-data:
