version: "3"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    restart: always
    command: mongod
    volumes:
      - ./mongodata/mongodb:/data/db

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
