version: '3.8'

services:
  auth-service:
    build:
      context: ..
      dockerfile: ../game-event-server/Dockerfile
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/auth-service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - msa-network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  mongodb:
    image: mongo:7
    container_name: auth-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - msa-network
    command: mongod --wiredTigerCacheSizeGB 1

  redis:
    image: redis:7-alpine
    container_name: auth-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - msa-network
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  mongodb_data:
  redis_data:

networks:
  msa-network:
    external: true
