version: '3.8'
services:
  game-event-server:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    restart: always
    networks:
      - app-network

  mongodb:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'  # AMQP 프로토콜
      - '15672:15672'  # 관리 UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:
